topics:
  terrain_map: /terrain_map
  body_plan: /body_plan
  discrete_body_plan: /discrete_body_plan

global_body_planner:
  update_rate: 1
  num_calls: 1            # Number of times to call the planner
  replan_time_limit: 1.0  # Minimum amount of time to run the planner (will replan to find better solutions until this duration is up)
  algorithm: rrt-connect  # rrt-connect or rrt-star-connect

terrain_map_publisher:
  update_rate: 10
  map_data_source: csv
  terrain_type: slope     # slope or rough terrain

grid_map_visualization:
  grid_map_topic: /terrain_map
  grid_map_visualizations:
    - name: elevation_points
      type: point_cloud
      params:
        layer: elevation
